### ISSUE TITLE
Feature Request: Allow controlling swipe %

### ISSUE THREAD

**Issue by rohan20** [husainazkas/slidable_button#3]
Would be nice to set a swipe % for which the swipe is considered as completed. Currently, [it's hardcoded at 50%](https://github.com/husainazkas/slidable_button/blob/master/lib/src/slidable_button.dart#L233) but I'd like to have something like 90% or even 100%. Happy to submit a PR.

Thank you for your great work on this!

**Comment by rohan20** [comment]
PR submitted [here](https://github.com/husainazkas/slidable_button/pull/4)

**Comment by husainazkas** [comment]
Thank you for the good improvement, I'll add it into an optional behavior ASAP

**Comment by husainazkas** [comment]
PR has merged. I'll close this issue. Thanks before!
