### ISSUE TITLE
Unable to change the slider position dynamically via setState

### ISSUE THREAD

**Issue by Charita-Ramaswamy** [husainazkas/slidable_button#5]
The initial position of SlidableButton is set to "left". After some async operation, I am setting the initial position value to "right". The code is getting called after setState however the slider position is still the same i.e. "left". Kindly help.....

**Comment by husainazkas** [comment]
Can you show your code?

**Comment by francescolodi-vicasystem** [comment]
I have the same problem, initialPosition is not always evaluated. Have you found some solution? Thanks!

**Comment by husainazkas** [comment]
@Charita-Ramaswamy @vicasystem 
It's caused I didn't override didUpdateWidget to update controller value if initialPosition changed. As you know that initial is initial, it's just first time position while widgets are being built.

To evaluated the position state you need to use controller then update the value of the controller to either 0.0 or 1.0.

But if you still need to rebuild widget with new initial position without controller, I will update soon as your needs. Thank you for your feedback!
